### ISSUE TITLE
[AP] Style Suite: Trying to get property 'ap_postbit_style' of non-object 

### ISSUE THREAD

**Issue by FortreeForums** [FortreeForums/FortreeForums#29]
#0 src/addons/apathy/StyleSuite/Repository/Styles.php(38): XF::handlePhpError(8, '[E_NOTICE] Tryi...', '/home/fortreef/...', 38, Array)

#1 src/addons/apathy/StyleSuite/Pub/Controller/Postbit.php(19): apathy\StyleSuite\Repository\Styles->findPostbitStyle()

#2 src/XF/Mvc/Dispatcher.php(350): apathy\StyleSuite\Pub\Controller\Postbit->actionIndex(Object(XF\Mvc\ParameterBag))

#3 src/XF/Mvc/Dispatcher.php(261): XF\Mvc\Dispatcher->dispatchClass('apathy\\StyleSui...', 'Index', Object(XF\Mvc\RouteMatch), Object(apathy\StyleSuite\Pub\Controller\Postbit), NULL)

#4 src/XF/Mvc/Dispatcher.php(113): XF\Mvc\Dispatcher->dispatchFromMatch(Object(XF\Mvc\RouteMatch), Object(apathy\StyleSuite\Pub\Controller\Postbit), NULL)

#5 src/XF/Mvc/Dispatcher.php(55): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))

#6 src/XF/App.php(2326): XF\Mvc\Dispatcher->run()

#7 src/XF.php(488): XF\App->run()

#8 index.php(20): XF::runApp('XF\\Pub\\App')

#9 {main}

this happens randomly with usernames, titles, and postbits.

**Comment by FortreeForums** [comment]
This popped back up with userrnames



    ErrorException: [E_NOTICE] Trying to get property 'ap_username_style' of non-object src/addons/apathy/StyleSuite/Repository/Styles.php:16 

    Generated by: Unknown account Feb 24, 2021 at 3:10 PM 

Stack trace

#0 src/addons/apathy/StyleSuite/Repository/Styles.php(16): XF::handlePhpError(8, '[E_NOTICE] Tryi...', '/home/fortreef/...', 16, Array)
#1 src/addons/apathy/StyleSuite/Pub/Controller/Username.php(27): apathy\StyleSuite\Repository\Styles->findUsernameStyle(Object(SV\DailyStatistics\XF\Entity\User))
#2 src/XF/Mvc/Dispatcher.php(350): apathy\StyleSuite\Pub\Controller\Username->actionIndex(Object(XF\Mvc\ParameterBag))
#3 src/XF/Mvc/Dispatcher.php(261): XF\Mvc\Dispatcher->dispatchClass('apathy\\StyleSui...', 'Index', Object(XF\Mvc\RouteMatch), Object(apathy\StyleSuite\Pub\Controller\Username), NULL)
#4 src/XF/Mvc/Dispatcher.php(113): XF\Mvc\Dispatcher->dispatchFromMatch(Object(XF\Mvc\RouteMatch), Object(apathy\StyleSuite\Pub\Controller\Username), NULL)
#5 src/XF/Mvc/Dispatcher.php(55): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#6 src/XF/App.php(2326): XF\Mvc\Dispatcher->run()
#7 src/XF.php(488): XF\App->run()
#8 index.php(20): XF::runApp('XF\\Pub\\App')
#9 {main}

**Comment by FortreeForums** [comment]
changing

`return $style;`

to

`	if(is_object($visitor))
	{
        	return $style;
	}`

will hopefully solve this, if the logic in [this thread](https://xenforo.com/community/threads/fetching-elements-from-sometimes-empty-finder-results.135918/) is understood correctly.

**Comment by FortreeForums** [comment]
`	if($user_id)
	{
		$style = $finder->where('user_id', $user_id)->fetchOne()->ap_username_style;

		return $style;
	}`

did the trick, but now we get


Error: Call to a member function fetchOne() on null in src/addons/apathy/StyleSuite/Pub/Controller/Profile.php at line 28

    apathy\StyleSuite\Pub\Controller\Profile->actionIndex() in src/XF/Mvc/Dispatcher.php at line 350
    XF\Mvc\Dispatcher->dispatchClass() in src/XF/Mvc/Dispatcher.php at line 261
    XF\Mvc\Dispatcher->dispatchFromMatch() in src/XF/Mvc/Dispatcher.php at line 113
    XF\Mvc\Dispatcher->dispatchLoop() in src/XF/Mvc/Dispatcher.php at line 55
    XF\Mvc\Dispatcher->run() in src/XF/App.php at line 2326
    XF\App->run() in src/XF.php at line 488
    XF::runApp() in index.php at line 20

**Comment by FortreeForums** [comment]
We also need to address how each control panel looks to guests

**Comment by FortreeForums** [comment]
Fixed as of 0da20d8

**Comment by FortreeForums** [comment]
Fixed as of 0da20d8
