### ISSUE TITLE
[AP] Style Suite:  LogicException

### ISSUE THREAD

**Issue by FortreeForums** [FortreeForums/FortreeForums#35]
LogicException: Template public:ap_profile_settings error: Entity is read only src/XF/Mvc/Entity/Entity.php:579

#0 src/XF/Mvc/Entity/Entity.php(567): XF\Mvc\Entity\Entity->set('xfa_cui_params', Array)
#1 src/addons/XFA/CustomUsernameIcons/XF/Template/Templater.php(45): XF\Mvc\Entity\Entity->__set('xfa_cui_params', Array)
#2 [internal function]: XFA\CustomUsernameIcons\XF\Template\Templater->fnUsernameLink(Object(SV\StandardLib\XF\Template\Templater), false, Object(SV\DailyStatistics\XF\Entity\User), true, Array)
#3 src/XF/Template/Templater.php(1103): call_user_func_array(Array, Array)
#4 internal_data/code_cache/templates/l1/s2/public/ap_profile_settings.php(79): XF\Template\Templater->func('username_link', Array)
#5 src/XF/Template/Templater.php(1626): XF\Template\Templater->{closure}(Object(SV\StandardLib\XF\Template\Templater), Array, NULL)
#6 src/XF/Template/Template.php(24): XF\Template\Templater->renderTemplate('ap_profile_sett...', Array)
#7 src/XF/Mvc/Renderer/Html.php(48): XF\Template\Template->render()
#8 src/XF/Mvc/Dispatcher.php(458): XF\Mvc\Renderer\Html->renderView('apathy\\StyleSui...', 'public:ap_profi...', Array)
#9 src/XF/Mvc/Dispatcher.php(440): XF\Mvc\Dispatcher->renderView(Object(XF\Mvc\Renderer\Html), Object(XF\Mvc\Reply\View))
#10 src/XF/Mvc/Dispatcher.php(400): XF\Mvc\Dispatcher->renderReply(Object(XF\Mvc\Renderer\Html), Object(XF\Mvc\Reply\View))
#11 src/XF/Mvc/Dispatcher.php(58): XF\Mvc\Dispatcher->render(Object(XF\Mvc\Reply\View), 'html')
#12 src/XF/App.php(2326): XF\Mvc\Dispatcher->run()
#13 src/XF.php(488): XF\App->run()
#14 index.php(20): XF::runApp('XF\\Pub\\App')
#15 {main}

array(4) {
  ["url"] => string(26) "/account/profile-settings/"
  ["referrer"] => bool(false)
  ["_GET"] => array(0) {
  }
  ["_POST"] => array(0) {
  }
}

**Comment by FortreeForums** [comment]
Hopefully fixed as of  96d3b50
